### ISSUE TITLE
codecov is raising exception when collecting the reports, but not failing the build

### ISSUE THREAD

**Issue by elyezer** [codecov/codecov-python#160]
`codecov` is having trouble parsing the results and is failing silently. The build https://travis-ci.org/quipucords/quipucords/builds/431127410 passed but when expanding the codecov command output it shows the following:

```
$ codecov
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.15
==> Detecting CI provider
    Travis Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find /home/travis/build/quipucords/quipucords -not -path './bower_components/**' -not -path './node_modules/**' -not -path './vendor/**' -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
    Generating coverage xml reports for Python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 571, in _arcs
    ch = byte_chunks[byte]
KeyError: 32037
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/bin/coverage", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/cmdline.py", line 710, in main
    status = CoverageScript().command_line(argv)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/cmdline.py", line 455, in command_line
    total = self.coverage.xml_report(outfile=outfile, **report_args)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/control.py", line 647, in xml_report
    return reporter.report(morfs, outfile=outfile)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/xmlreport.py", line 56, in report
    self.report_files(self.xml_file, morfs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/report.py", line 84, in report_files
    report_fn(cu, self.coverage._analyze(cu))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/xmlreport.py", line 112, in xml_file
    branch_stats = analysis.branch_stats()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/results.py", line 144, in branch_stats
    exit_counts = self.parser.exit_counts()
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/misc.py", line 73, in _wrapped
    setattr(self, attr, fn(self))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 246, in exit_counts
    for l1, l2 in self.arcs():
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/misc.py", line 73, in _wrapped
    setattr(self, attr, fn(self))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 230, in arcs
    for l1, l2 in self.byte_parser._all_arcs():
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 631, in _all_arcs
    arcs.update(bp._arcs())
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coverage/parser.py", line 578, in _arcs
    raise Exception("Couldn't find chunk @ %d" % byte)
Exception: Couldn't find chunk @ 32037
    Error running `coverage xml -i`: None
    + /home/travis/build/quipucords/quipucords/coverage.xml bytes=0
==> Appending environment variables
    + TRAVIS_OS_NAME
    + TRAVIS_PYTHON_VERSION
==> Uploading
    .url https://codecov.io
    .query commit=081006b1758ce8efedc6eb9dfab271111def73e3&branch=master&job=431127411&pr=false&service=travis&build=4528.1&slug=quipucords%2Fquipucords&package=py2.0.15
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/quipucords/quipucords/commit/081006b1758ce8efedc6eb9dfab271111def73e3

Done. Your build exited with 0.
```

Accessing the URL provided at the very bottom of the report it says `There was an error processing coverage reports.`

Tried to rerun the build a couple times and it always raise the same exception.

**Comment by thomasrockhu** [comment]
I'm going to close this out due to age, but if this is still a need, please open an issue on our [community boards](https://community.codecov.io)
