### ISSUE TITLE
Codecov crashes on Semaphore build due to missing env var SEMAPHORE_BUILD_NUMBER

### ISSUE THREAD

**Issue by Helveg** [codecov/codecov-python#219]
Running

```
pip install codecov
codecov
```

on Semaphore CI fails with the following error:
```

Traceback (most recent call last):
--
  | File "/home/semaphore/.pyenv/3.7/bin/codecov", line 8, in <module>
  | sys.exit(main())
  | File "/home/semaphore/.pyenv/3.7/lib/python3.7/site-packages/codecov/__init__.py", line 365, in main
  | build=os.getenv('SEMAPHORE_BUILD_NUMBER') + '.' + os.getenv('SEMAPHORE_CURRENT_THREAD'),
  | TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
  | exit code: 1 duration: 0s

```

**Comment by Helveg** [comment]
Also important to notice is that the `SEMAPHORE` env var that is being checked to determine that Semaphore CI is being used, is also set to true if Semaphore 2.0 is being used.
