### ISSUE TITLE
--help wants a repo in cwd

### ISSUE THREAD

**Issue by ionelmc** [codecov/codecov-python#23]
That option shouldn't require any repository to be setup. 
Eg:
```
C:\Users\ionel_000>codecov --help
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "c:\Python27\Scripts\codecov-script.py", line 9, in <module>
    load_entry_point('codecov==1.1.7', 'console_scripts', 'codecov')()
  File "c:\Python27\lib\site-packages\codecov\__init__.py", line 240, in cli
    data, codecov = main()
  File "c:\Python27\lib\site-packages\codecov\__init__.py", line 216, in main
    branch = subprocess.check_output('git rev-parse --abbrev-ref HEAD', shell=True)
  File "c:\Python27\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git rev-parse --abbrev-ref HEAD' returned non-zero exit status 128
```

**Comment by stevepeak** [comment]
Thanks for pointing this out. I'll fix this in my next release.
