### ISSUE TITLE
Failing on python 3.2 on Travis-CI

### ISSUE THREAD

**Issue by gappleto97** [codecov/codecov-python#46]
```python
$ coverage run main.py
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.5/bin/coverage", line 9, in <module>
    load_entry_point('coverage==4.0.2', 'console_scripts', 'coverage')()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
    return self.resolve()
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/__init__.py", line 13, in <module>
    from coverage.control import Coverage, process_startup
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/control.py", line 15, in <module>
    from coverage.annotate import AnnotateReporter
  File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/coverage/annotate.py", line 85
    dest.write(u'  ')
                   ^
SyntaxError: invalid syntax
```

**Comment by stevepeak** [comment]
This error looks like it comes from the `coveragepy` package. Are you able to install this package in your environment?

Lets try: `pip install coverage==3.7.1 codecov` (I recall hearing issues with 3.2 and coverage v4)

**Comment by gappleto97** [comment]
This definitely fixes things. I added a flag to my `.travis.yml` script to only install 3.7.1 on python 3.2.*. I've also made sure that all of my coverage checks are done with allowed failure. Thanks for the help.
